function err = fcell(vc, ic, par)
    err = ...
        fphotocurr(par) - ...
        fdiode(vc + par.Rs.*ic, par) - ...
        par.Gsh.*(vc + par.Rs.*ic) - ...
        ic;
    err = err(:); % not necessary, provided for consistency with the following
end
